### ISSUE TITLE
Add sodiumoxide (libsodium) benchmarks

### ISSUE THREAD

**Issue by briansmith** [briansmith/crypto-bench#13]
The library is at https://github.com/dnaq/sodiumoxide.

I had tried to do this before, but I had trouble getting sodiumoxide to build because it couldn't find libsodium. I think [libsodium-sys](https://github.com/zonyitoo/libsodium-sys) may be helpful, because it builds and links libsodium itself?

@zonyitoo @dnaq Do I understand the above correctly, that sodiumoxide should now work even on systems that don't have libsodium installed already?

**Comment by briansmith** [comment]
Work on this has started in #18. We're having build issues on Linux, but otherwise it looks good to go.

**Comment by JohnHeitmann** [comment]
This sodiumoxide PR will unblock AES-GCM and Chacha20-Poly1305: https://github.com/dnaq/sodiumoxide/pull/130
