### ISSUE TITLE
Stop pulling crates from github

### ISSUE THREAD

**Issue by kkartaltepe** [briansmith/crypto-bench#31]
Just an issue I ran into when using this repository is that it references the github repo for a number of crates. Various projects use various methods working with git and its quite likely that at any given time one of the git HEADs will be broken or may induce breaking changes since this crate has been updated. In my case, tests for the `ring` crate failed but switching to the most recent crates.io release resolved all issues.

In addition to avoiding potentially broken master branches, using crates.io releases is also much more representative of expected performance as most people are not going to be linking against the GitHub repository.

**Comment by nornagon** [comment]
The `ring` build is currently broken, for instance, but the crates.io version works fine :)

**Comment by briansmith** [comment]
I agree we should switch the default configuration to use the latest release version of every crate.

**Comment by briansmith** [comment]
This was done in b2a04659abd2d3c5a3387e7b39ed7f128e71a2d0.
