### ISSUE TITLE
Use stable Rust instead of nightly Rust

### ISSUE THREAD

**Issue by briansmith** [briansmith/crypto-bench#41]
Benchmarks on nightly Rust aren't as useful as benchmarks on stable Rust would be since most users  want to use stable Rust (at least, according to my experience).

I would be happy to switch to either https://crates.io/crates/bencher or https://crates.io/crates/criterion; see https://www.reddit.com/r/rust/comments/8tplwr/what_is_the_standard_way_to_run_benchmarks_in/ for more discussion. One problem may be "black box" support, or the lack of it.

**Comment by hauleth** [comment]
I am using Criterion in benching Octavo and it is quite pleasant. Also as soon as bheisler/criterion.rs#130 lands it will be perfect solution as it will be able to measure CPU cycles instead of wall time, as this is metric commonly used in crypto benching.
