### ISSUE TITLE
Adding new primitives/constructions?

### ISSUE THREAD

**Issue by brycx** [briansmith/crypto-bench#45]
I was wondering whether crypto-bench would accept adding implementations of other primitives/constructions than those listed in the README? Things like BLAKE2*, etc.

I was also wondering if the the ChaCha20-Poly1305 benchmark-listing, in the README, cover a XChaCha20-Poly1305 implementation? I'm asking because sodiumoxide is listed to have benchmarks for Salsa20-Poly1305, when in fact it calls a XSalsa20-Poly1305 implementation.

**Comment by briansmith** [comment]
Of the things you mentioned, XChaCha20-Poly1305 would be the most interesting to me. It would probably be a while before I would have time to review PRs for the others, due to time constraints.

**Comment by brycx** [comment]
I'm finishing a PR for my own library, which will include benches for PBKDF2, SHA-512, ChaCha20Poly1305. I can certainly add XChaCha20Poly1305 as well.

My other question still stands though: Is it intentional that the call to `xsalsa20poly1305` is listed as Salsa20-Poly1305 and not XSalsa20-Poly1305?

**Comment by briansmith** [comment]
No, it probably wasn't intentional.

Anyway, thank you for your contributions to this project. Unfortunately, I have to stop accepting contributions for a while, so I'm going to close this issue.
